### ISSUE TITLE
No hay listas ya, es una base de datos gestionada por Hibernate

### ISSUE THREAD

**Issue by Lainezz** [abrahamr110/ProyectoStockControl#1]
https://github.com/abrahamr110/ProyectoStockControl/blame/a5a5aef9365e242ff4583f36826adeb282f8df51/src/main/java/com/es/stockcontrol/repository/ProductoRepository.java#L10

La lista ya no es válida como estructura de almacenamiento de datos. Hay que usar una base de datos MySQL.

**Comment by abrahamr110** [comment]
Arreglado.
https://github.com/abrahamr110/ProyectoStockControl/commit/09648b939f0683acab3857e07eda063f4a6f3748
