### ISSUE TITLE
EntityManagerFactory y EntityManager NO pueden estar en la clase Main

### ISSUE THREAD

**Issue by Lainezz** [abrahamr110/ProyectoStockControl#2]
https://github.com/abrahamr110/ProyectoStockControl/blame/a5a5aef9365e242ff4583f36826adeb282f8df51/src/main/java/com/es/stockcontrol/repository/UserRepository.java#L16

Las clases EntityManagerFactory y EntityManager no deben estar en la clase main. Como opción, podéis crear una nueva clase "HibernateUtils", por ejemplo... y poner ambas clases ahí... como opción para salir del paso.

**Comment by abrahamr110** [comment]
Arreglado.
https://github.com/abrahamr110/ProyectoStockControl/commit/09648b939f0683acab3857e07eda063f4a6f3748
